---
# yamllint disable rule:line-length
name: Linux build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'manual/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'manual/**'
  schedule:
    - cron: "10 */6 * * *"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04 
    name: huma
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Before build
        run: |
          python ./ci/github-pre-build.sh

